version: 2.1
jobs:
  build:
    machine:
      image: windows-server-2019-vs2019:stable
    steps:
    - checkout
    - run:
        name: "Build"
        command: dotnet build ./CalculatorVS > /artifact
    - store_artifacts:
        path: ./CalculatorVS/bin/Debug/netcoreapp3.1
        destination: BuiltFile
    resource_class: windows.medium
    shell: powershell.exe -ExecutionPolicy Bypass
  
  test:
    machine:
      image: windows-server-2019-vs2019:stable
    steps:
    - checkout
    - run: mkdir test-reports
    - run:
        name: Download Selenium
        command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
    - run:
        name: Start Selenium
        command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
        background: true
        

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build