version: 2.1
jobs:
  build:
    machine:
      image: windows-server-2019-vs2019:stable
    resource_class: windows.medium
    steps:
    - checkout
    - run:
        name: "Build"
        command: dotnet build ./CalculatorVS > /artifact
    - store_artifacts:
        path: ./CalculatorVS/bin/Debug/netcoreapp3.1
        destination: BuiltFile
    shell: powershell.exe -ExecutionPolicy Bypass
  
  test:
    machine:
      image: windows-server-2019-vs2019:stable
    resource_class: windows.medium
    steps:
    - checkout
    - run:
          name: "Run Application Tests"
          command: dotnet test "NUnit.Test/NUnit.Test.csproj" --logger trx 
    - run:
          name: test results
          when: always
          command: |
              dotnet tool install -g trx2junit
              export PATH="$PATH:/root/.dotnet/tools"
              trx2junit tests/**/TestResults/*.trx
      - store_test_results:
          path: tests/TestResults
      - store_artifacts:
          path: tests/TestResults
          destination: TestResults

        

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
