version: 2.1
jobs:
  build:
    machine:
      image: windows-server-2019-vs2019:stable
    resource_class: windows.medium
    steps:
    - checkout
    - run:
        name: "Build"
        command: dotnet build ./CalculatorVS > /artifact
    - store_artifacts:
        path: ./CalculatorVS/bin/Debug/netcoreapp3.1
        destination: BuiltFile
    shell: powershell.exe -ExecutionPolicy Bypass
  
  test:
    machine:
      image: windows-server-2019-vs2019:stable
    resource_class: windows.medium
    steps:
    - checkout
    - run: mkdir test-reports
    - run:
          name: "Run Application Tests"
          command: dotnet test "NUnit.Test/NUnit.Test.csproj" --logger trx > /artifact
    - store_artifacts:
          path: ./CalculatorVS/NUnit.Test/TestResults
          destination: TestResults
        

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build