version: 2.1
commands:
  nococid-command-start-workflow:
    steps:
      - run: curl --header "Content-Type:application/json" --data '' -X POST "http://toan0701.ddns.net:9080/Nococid/api/Listeners/CircleCI/start-workflow?sprint_id=a9bd72b6-f57d-4721-23eb-08d8f0dcf11c&branch_id=e576a1e9-7c5d-41d0-ee1f-08d8f040ef2c&circle_workflow_id=${CIRCLE_WORKFLOW_ID}"
  nococid-command-job-done:
    steps:
      - run: curl --header "Content-Type:application/json" --data '' -X POST "http://toan0701.ddns.net:9080/Nococid/api/Listeners/CircleCI/job-done?circle_workflow_id=${CIRCLE_WORKFLOW_ID}&circle_job_num=${CIRCLE_BUILD_NUM}&stage=${CIRCLE_STAGE}"
  nococid-command-end-workflow:
    steps:
      - run: curl --header "Content-Type:application/json" --data '' -X POST "http://toan0701.ddns.net:9080/Nococid/api/Listeners/CircleCI/end-workflow?sprint_id=a9bd72b6-f57d-4721-23eb-08d8f0dcf11c&circle_workflow_id=${CIRCLE_WORKFLOW_ID}&gh_username=${CIRCLE_PROJECT_USERNAME}&gh_repository=${CIRCLE_PROJECT_REPONAME}"
  abc:
    steps:
      - run: abcxyz
jobs:
  nococid-start-workflow:
    machine:
      image: windows-server-2019-vs2019:stable
    steps:
    - nococid-command-start-workflow
  nococid-end-workflow:
    machine:
      image: windows-server-2019-vs2019:stable
    steps:
    - nococid-command-end-workflow
  build:
    machine:
      image: windows-server-2019-vs2019:stable
    resource_class: windows.medium
    steps:
    - checkout
    - run:
        name: "Build"
        command: dotnet build ./CalculatorVS
    - store_artifacts:
        path: ./CalculatorVS/bin/Debug/netcoreapp3.1
        destination: BuiltFile
  test:
    machine:
      image: windows-server-2019-vs2019:stable
    resource_class: windows.medium
    steps:
    - checkout
    - run:
        name: "Test"
        command: |
            dotnet build./NUnit.Test
            dotnet test./NUnit.Test --no-build --logger "trx"
    - run:
        shell: powershell.exe -ExecutionPolicy Bypass
        name: "Test Results"
        when: always
        command: |
            dotnet tool install -g trx2junit
            trx2junit./NUnit.Test/TestResults/*.trx
    - store_test_results:
        path: ./NUnit.Test/TestResults
    - store_artifacts:
        path: ./NUnit.Test/TestResults
        destination: TestResults
workflows:
  version: 2
  workflow:
    jobs:
      - build:
          requires:
            - nococid-start-workflow
          pre-steps:
            - nococid-command-job-done
      - test:
          requires:
            - nococid-start-workflow
          pre-steps:
            - nococid-command-job-done
      - test:
          name: tg
          pre-steps:
            - nococid-command-job-done
          requires:
            - nococid-start-workflow
      - nococid-start-workflow
      - nococid-end-workflow:
          requires:
            - build
            - tg
