version: 2.1
jobs:
  build:
    machine:
      image: windows-server-2019-vs2019:stable
    resource_class: windows.medium
    steps:
    - checkout
    - run:
        name: "Build"
        command: dotnet build ./CalculatorVS > /artifact
    - store_artifacts:
        path: ./CalculatorVS/bin/Debug/netcoreapp3.1
        destination: BuiltFile
    shell: powershell.exe -ExecutionPolicy Bypass
  
  test:
    machine:
      image: windows-server-2019-vs2019:stable
    resource_class: windows.medium
    steps:
    - checkout
    - run: mkdir test-reports
    - run:
          name: "Run Application Tests"
          command: dotnet.exe test -v n --results-directory:test_file --logger "console;verbosity=detailed"
    - store_artifacts:
          path: C:\Users\circleci\project\test_file
        

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build